= Technopolis

Technopolis is a globally interconnected micro-blogging platform inspired by Misskey. 

It was developed to replace Misskey's cumbersome web API and make it more robust.

== TO DO and NOT TO DO list

We are going to implement all of Misskey's features, but we are not going to implement some unnecessary features.

=== TO DO

Emoji reaction:: 
Emoji reaction is the primary reason to use misskey. Of course, Technopolis will implement it.
File drive:: This is a useful feature for illustrators and others who want to re-submit images that have been posted in the past. It may be simpler than Misskey.
Custom timeline:: A powerful custom timeline that allows you to narrow down your posts with regular expressions.
AsciiDoc:: AsciiDoc boasts Markdown-like readability and more powerful expressiveness than Markdown.

=== NOT TO DO

Reversi:: Is this _**REALLY**_ necessary? Is there a reason why the preinstalled solitaire or pinball on Windows isn't good enough?
Live stream:: This feature is only available in misskey.io, not in misskey.
Chat:: (Maybe I'll implement it.) See https://github.com/technopolis-microblog/Technopolis/issues/11[this issue.]
Static page:: Isn't github.io or Netlify enough?
Misskey Flavored Markdown:: The letters rotate and jump... the marquee tag is obsolete, isn't it?
Misskey Room:: Why was this implemented in Misskey?

== License

Copyright (c) 2020 Technopolis Developers.

licensed under the gnu affero general public license version 3(link:./license[license] or https://opensource.org/licenses/agpl-3.0)

== Open source software

This software includes several software. Details see below.

=== yarn v2
[source]
----
BSD 2-Clause License

Copyright (c) 2016-present, Yarn Contributors.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
