= Technopolis

Technopolis aims to be a lightweight and elegant federated micro-bloging platform that implements only the features you need.

Basically, it will be developed as a Misskey clone, but we don't want to implement some of the features.

== TO DO and NOT TO DO list

=== TO DO

Emoji reaction:: 
Emoji reaction is the primary reason to use misskey. Of course, Technopolis will implement it.
File drive:: This is a useful feature for illustrators and others who want to re-submit images that have been posted in the past. It may be simpler than Misskey.
Custom timeline:: A powerful custom timeline that allows you to narrow down your posts with regular expressions.
AsciiDoc:: AsciiDoc boasts Markdown-like readability and more powerful expressiveness than Markdown.

=== NOT TO DO

Reversi:: Is this _**REALLY**_ necessary? Is there a reason why the preinstalled solitaire or pinball on Windows isn't good enough?
Live stream:: This feature is only available in misskey.io, not in misskey.
Chat:: (Maybe I'll implement it.) See https://github.com/technopolis-microblog/Technopolis/issues/11[this issue.]
Static page:: Isn't github.io or Netlify enough?
Misskey Flavored Markdown:: The letters rotate and jump... the marquee tag is obsolete, isn't it?
Misskey Room:: Why was this implemented in Misskey?

== License

licensed under the gnu affero general public license version 3(link:./license[license] or https://opensource.org/licenses/agpl-3.0)

== Author

https://www.sc3.fun[銀猫さん] (link:mailto:silverscat_3@mail.sc3.fun[silverscat_3@mail.sc3.fun])

