openapi: 3.0.0
info:
  title: Technopolis
  version: '1.0'
  contact:
    name: 銀猫さん
    url: 'https://www.sc3.fun'
    email: silverscat_3@mail.sc3.fun
  license:
    name: GNU Affero General Public License v3.0
    url: 'https://www.gnu.org/licenses/agpl-3.0.txt'
servers: []
paths:
  /apps:
    post:
      summary: アプリケーションの作成 Create an application
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  website:
                    type: string
                  redirect_uri:
                    type: string
                  client_id:
                    type: string
                  client_secret:
                    type: string
                  vapid_key:
                    type: string
                  '':
                    type: string
              examples: {}
      operationId: post-apps
      security: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_name:
                  type: string
                redirect_uris:
                  type: string
                scopes:
                  type: string
                website:
                  type: string
                '':
                  type: string
components:
  schemas: {}
